### ISSUE TITLE
windows compatibility

### ISSUE THREAD

**Issue by ppigazzini** [lucasart/c-chess-cli#1]
@lucasart gcc from mingw-w64 (WinAPI) fails to build `c-chess-cli.exe`, wait.h doesn't exist in WinAPI, see https://stackoverflow.com/questions/7841187/visual-c-doesnt-have-sys-wait-h/7841250#7841250
```
$ make
gcc -std=gnu99 -mpopcnt -O3 -flto -Wfatal-errors -Wall -Wextra -Wshadow -DNDEBUG ./*.c -o c-chess-cli -s
./engine.c:18:10: fatal error: sys/wait.h: No such file or directory
   18 | #include <sys/wait.h>
```

gcc from msys repo (POSIX emulated) builds `c-chess-cli.exe`, but this should run only in a msys2 shell.

**Comment by lucasart** [comment]
Actually, I don't use 'sys/wait.h'. This was for waitpid, but I figured it was pointless. Rather than write 'quit\n' and wait, then kill after timeout, may as well just kill straight away.

There's still line buffering which is broken on Windows, so I don't expect it will work.

**Comment by lucasart** [comment]
Reference for Windows
https://docs.microsoft.com/en-us/windows/win32/procthread/creating-a-child-process-with-redirected-input-and-output

**Comment by d3vv** [comment]
@lucasart if u have no windows hosts then u could to use MXE (M cross environment) under most unix-like os:

https://mxe.cc/

**Comment by lucasart** [comment]
won't fix. win32 API is too far from POSIX. i have no personal interest in doing it, and no one else seems ready to do the work. so closing.
