### ISSUE TITLE
FRC, and some other questions for OpenBench

### ISSUE THREAD

**Issue by AndyGrant** [lucasart/c-chess-cli#14]
So I was tempted to use c-chess-cli, and then got lazy. And now I'm trying to build a new version of cutechess since the primary version has broken support for FRC ... and well https://en.wikipedia.org/wiki/Dependency_hell what a cluster *#$!.  QT is such a nightmare that I would sooner learn how to account for Window's non-posix. 

So under the assumption that I, or someone else adds support for Windows compilation or at least running on a Windows machine, here are some questions and comments You can answer them, or just tell me to look at the source, up to you.

1) How good is the support for Fischer Random Chess? The readme says that a book will auto detect FRC. Does that mean it will identify a particular position is an FRC one, and tell the engine. Or that if a single FRC position occurs in the book, then it will tell the engine? I feel like there could be a problem there, but I'm not convinced.

2) Is there support for Table-base Adjudication? If not, you could use https://github.com/AndyGrant/Pyrrhic/ , which as far as I can tell, is far more portable than Fathom. I don't really care about this one though, just a nice thing to have.

3) What kind of reporting (if any) can I look to parse when something bad happens? Crashes, Disconnects, Stalls, Illegal, Timeloss, etc. I don't care about tracking down debug information like the people on talkchess. I just want to be able to slap a label on a game that went wrong, so that I can report it back to the server.

4) Is there something like cutechess's "restart", which says that even if something goes bad, just restart the engine and continue playing games.

5) For draw adjudication, can I pass a 3rd value so that instead of being ``moves,score`` its ``moveNumber,moves,score`` which then only applys adjudication after the moveNumber-th move.

6) Is there a way we can shuffle the openings of a book, instead of just starting at a random location? Also, what happens when I provide a book of 4 million EPDs? Is this a problem?

7) What kind of resolution do I have when passing something like ``tc 10.0+.1`` ? Can I go as far as to do something like ``12.345+0.012345"? I would assume yes.

**Comment by lucasart** [comment]
1. FRC detection is done at position level. So an EPD file can mix. In fact chess960.epd has some openings auto detected as non FRC. Those are all the 960 openings where KRR are in the standard position and other pieces are shuffled. The `setoption name UCI_Chess960` comes along with each `ucinewgame`.

2. No TB adjudication. I can add pyrrhic, if it's easy to integrate.

3. Same as cutechess-cli. For the part you don't care about, I think it has better logging which is useful for engine development (but not something that the OpenBench client will parse or care about).

4. No. This would have to be managed externally. I think it is best to stop the test. Force people to debug their engines.

5. No. It would be interesting to do some research on the topic (ie. proper statistics on time saved by adjudicating vs. error introduced). It's easy to implement, but I'm not convinced about the need for this feature (never seen any evidence to back it, beyond the usual handwaiving on forums).

6. No. Again this is a mis feature IMO. The correct solution is to shuffle the book, and read sequentially from random starting position, that way you never repeat (until N openings were played). With random seek for every position you repeat every sqrt(N) time on average (aka. birthday paradox). File size: sky is the limit, O(1) not O(n), which is another reason I don't like the random re-seek approach btw.

7. No limit. Parsed with sscanf as double.

**Comment by AndyGrant** [comment]
1. Okay, settled. I trust your implementation. Very elegant. Ethereal also "self sets" FRC if you present it with positions that are illegal to standard chess but not FRC (weird castling rights).

2. Don't waste your time. If I want it, I'll add it and send the PR your way myself.

3. Perfect, parsing code remains similar if not exact.

4. Fair enough, honestly. What about time losses though? That is a different "classification" of bug. I can give someone the benefit of the doubt with timelosses, but if you are crashing out you are not staying on OpenBench. You don't need massive compute if you are not a stable bug free engine. 

5. You are probably right, and I have no reason to claim a movenumber matters. So ignore this.

6. I think we said the same thing? Shuffle book, start reading in order. I did not want to take a random position from the same sample at the start of every new game. That would be insane, which is what you were conveying to me.

7. Perfect. I did not expect someone like you to naively assume the format to be N digits, but I wanted to check since I checked in cutechess.

You can close this if you don't like having an open issue -- this just seemed like my best way to contact you.

**Comment by lucasart** [comment]
4. Time losses aren't fatal errors. They are simply reported to stdout (same as cutechess-cli), counting the game as lost for the offending engine. Only I/O errors are fatal. If we can't read from the pipe, the engine crashed. And if we can't read past time limit, plus a conservative margin, then it's "connection stalls" which is also fatal.

**Comment by lucasart** [comment]
6. To be clear :it's the user's responsibility to shuffle the book. This is trivial, just `shuf ordered.epd > shuffled.epd`.

**Comment by lucasart** [comment]
I'm working on better solution, where the EPD file given can be shuffled or not. Works as follows:
* builds an index[] of file offsets for each line
* if `-random` then shuffle the index
* read from the index sequentually from the beginning. first opening at `index[0]`, etc. , until `index[n-1]`, then loop modulo `n`

That way we get perfect n cycles (no birthday paradox sqrt(n) repetition as in cutechess), and consistent treatment of both cases (shuffle the index being just an extra pre-processing in the `-random` case).

The memory usage of `index[]` will be order of `sizeof(size_t) * numberOfLines`, and the pre-processing step is another `O(n)` which should be fast in practice (just reading the file once sequentually and recording offsets).
