### ISSUE TITLE
Elo differences or rankings.

### ISSUE THREAD

**Issue by vondele** [lucasart/c-chess-cli#30]
This is a feature request, not a real issue.

It would be convenient (especially for multi-engine tournaments), if one could get a ranking or LOS or Elo differences (+ error bars) of the engines in the tournament. Now, I need to write the pgn file and analyze with an external tool (I'm using something like `./ordo -p out-para02.pgn -a 0.0 --draw-auto --white-auto -s 100`, but any reasonable will be fine with me).

**Comment by lucasart** [comment]
Yes, use ordo or bayeselo for now (and `-rounds` to split the tournament). What I can do as a stepping stone, is to display (at regular intervals specified by the user) the (W,L,D) triplet for each pair. Like this:
```
Stockfish vs. Ethereal: 10 - 5 - 15 [58.3%]
Stockfish vs. Komodo: 9 - 4 - 8 [61.9%]
Ethereal vs. Komodo: 7 - 9 - 12 [46.4%]
```
As for an ELO model, I'm a bit reluctant to do that:
* basic model (ELO Stat) is too flawed. I think that's what cutechess uses (not sure).
* Bayes Elo is too complicated, and not well documented (the huge and bloated C++ code base is the only real documentation).
* Ordo, I don't know. I suspect it's not simple either to implement the ordo algorithm.

If anyone has something light and self-explanatory, like a python script showing how to compute based on (W,L,D) pairs for N engines (round-robin or gauntlet, the latter involves more inference, of course), I'm interested. Maybe Michel has something like that somewhere.

**Comment by lucasart** [comment]
Steps:
- [ ] JobQueue must learn engine names dynamically. These are not known a priori (3 step waterfall logic: `name=` override from user, id name from engine, path from `cmd=`).
- [ ] JobQuene should print a table into a string buffer (which client code can print atomically).
- [ ] main() should print table at the end (always).
- [ ] options_parse(): add `-ratinginverval N` option (follow naming of cutechess-cli).
- [ ] thread_start(): display table when `idx % N == 0`.

**Comment by vondele** [comment]
Thanks, a table of game results would be a useful already.  

The main disadvantage I see from using an external tool is that it needs parsing files, and I'd like to avoid writing them if possible (especially pgn with 250 concurrency risks to bottleneck, but so far I didn't observe an issue).

Maybe @vdbergh has a suggestion for a good Elo model. And while we mention his name.... would be interesting to collect match results not just with W-D-L but using the pentanomial results if openings are repeated with alternating colours. We're now using them in fishtest, and I think they make increasingly sense.

**Comment by vondele** [comment]
Thinking about the table a little more. 

For me would be enough to display the expected score with error bar as in:
Stockfish vs. Ethereal: 10 - 5 - 15 [58.3%  +- X.Y%]

But there is no need for the O(N^2) results for me, within the tournament, just rank the engines with respect to their expected total score, there is no need to turn that into an Elo number (but why not). Error bars are definitely nice to have.
Stockfish : 30 - 10 - 15 [75% +- 5%]
Komodo: 15 -15 -15 [50% +- 5%]
Ethereal: [ ... ]

**Comment by lucasart** [comment]
> The main disadvantage I see from using an external tool is that it needs parsing files, and I'd like to avoid writing them if possible (especially pgn with 250 concurrency risks to bottleneck, but so far I didn't observe an issue).

You can use verbosity levels in PGN export: `-pgn out.pgn 0` will remove comments. Regarding Ordo, I bet it doesn't actually parse the PGN, but only reads headers (lines of the form `[...]`), so it should be fast (at least for parsing).

**Comment by lucasart** [comment]
> Thinking about the table a little more.
> 
> For me would be enough to display the expected score with error bar as in:
> Stockfish vs. Ethereal: 10 - 5 - 15 [58.3% +- X.Y%]
> 
> But there is no need for the O(N^2) results for me, within the tournament, just rank the engines with respect to their expected total score, there is no need to turn that into an Elo number (but why not). Error bars are definitely nice to have.
> Stockfish : 30 - 10 - 15 [75% +- 5%]
> Komodo: 15 -15 -15 [50% +- 5%]
> Ethereal: [ ... ]

That would be practical, but mathematically dubious, I think. The problem is that you have a different result distribution for each engine pair. When you aggregate like this, you are mixing these distributions, with weights being the relative number of games each pair has played. So it's not clear what you'd be calculating.

**Comment by vondele** [comment]
well it would reflect the expected score within the tournament (with that fixed set of engines etc). 
Interpretations beyond that are indeed speculative, but the numbers itself just reflect the data.

**Comment by vondele** [comment]
thinking more about it. I agree that when transitivity is broken in the ranking of engines, a linear ranking becomes dubious. (i.e. a>b, b>c, but c>a). 

So, probably one needs to skip the 'linear' idea, and instead present all pairs of results in the form of a matrix (which is equivalent to listing all scores). One could compute the LOS for each (ordered) pair and show that. Any permutation of engines in that matrix can be used. 

Nevertheless, assume we have enough games so that all losses are close to 0 or 100% in the matrix, there will be a small number of permutations that maximizes the number of 100% losses in the upper triangle. If everything is transitive, there will be only one (all all upper triangle elements are 100%, all lower 0%). If things are not transitive, a number of equivalent permutations might exist that all lead to the same, maximum number of 100% entries in the upper triangle. I have no suggestions on how to pick either of these equivalent permutations.

I have one more idea for a tournament mode based on these ideas, I will suggest it in a different issue.

**Comment by vdbergh** [comment]
@vondele I think it is pretty hopeless to try to output something which has real meaning with a quick hack.

Writing something like Ordo or BayesElo is conceptually simple since all one is doing is optimizing a very well behaved (convex) loss function (whatever the Elo model one wants to use). One can even keep the code relatively compact by using an external scientific library (e.g. https://www.gnu.org/software/gsl/ ). I have done this in Python using SciPy. But such a library would create a big dependency which goes against the aim of this project.

Personally when I was still working on GnuChess I never found the need for using an external rating tool troublesome. It was just part of the workflow.

**Comment by vondele** [comment]
right, that's why I suggested LOS calculations for each pair of engines, displayed in matrix form for easy viz. Well defined (I hope!) and simple to compute.

To do the ranking I have now to transfer a 582MB file from one place to another (), it is just not very convenient. I could of course also have more external tools on the remote machine, but that are also dependencies.

**Comment by vdbergh** [comment]
@vondele There is `ordoprep` which compactifies pgn's (the result is a pgn with only minimal headers and a result). Of course c-chess-cli could write such pgns...

The advantage of using a pgn as intermediary is that one can easily combine games from multiple tournaments.

**Comment by lucasart** [comment]
@vdbergh: Easy to do. But is it necessary ? A simple grep will do that:
```
$ grep '^\[' fat.pgn > slim.pgn
```
Also, there is verbosity=0 in c-chess-cli which doesn't generate PGN comments (if disk space is the constraint and `fat.pgn` won't fit, even before the grep).

**Comment by vdbergh** [comment]
@lucasart I thought one also needed the result. The output of ordoprep is something like
```
[White "youngkasparov"]
[Black "GuestHJDN"]
[Result "1-0"]
1-0
```
It is a format that both ordo and BayesElo understand. Without the 1-0 at least BayesElo will not parse the pgn correctly.

**Comment by lucasart** [comment]
@vdbergh: Hum. That's a bit dumb from BayesElo. Anyway, I pushed a patch 9f83e072bee580857f85c60a5ecf8a245d249365.
