### ISSUE TITLE
integrate xboard in test suite

### ISSUE THREAD

**Issue by lucasart** [lucasart/c-chess-cli#34]
- modify test/engine.c (which is a stand alone engine used for integration testing) to support xboard syntax.
- use it in `make.py -p test` to have a run that exercises xboard parsing in c-chess-cli.

@sderr you might be interested in that ? I would rather integrate the current xboard code in the test suite, before modifying it. From experience, I know how even trivial refactorings, that look obviously correct, can in fact break code.

**Comment by sderr** [comment]
I could try... but unless I'm mistaken, currently all tests are chess960, which is not yet supported in the pull request I submitted. I'd have to add that first.

**Comment by lucasart** [comment]
Found good documentation on xboard protocol: http://hgm.nubati.net/CECP.html.

I will work on this, which will be a good way for me to learn about xboard.

**Comment by lucasart** [comment]
To be honest, xboard is long dead and burried. Now all (stable and modern) chess engines use UCI, even those which used to be xboard in the past (such as GNU Chess, for example). The protocol itself was always poorly defined, and suffers from serious feature creep (backward compatibility preventing to clean up the mess).

In practice, there is only one person in the world who cares about this protocol, and he is the encyclopedia for it (HG Muller). So I've asked him for [clarifications on the CECP syntax](http://talkchess.com/forum3/viewtopic.php?f=7&t=76106&p=876819#p876819).
