### ISSUE TITLE
_WIN32 compat

### ISSUE THREAD

**Issue by d3vv** [lucasart/c-chess-cli#4]
for `str.c`  we need to use:

```
#ifdef _WIN32
#define flockfile _lock_file
#define funlockfile _unlock_file
#define getc_unlocked _fgetc_nolock
#endif
```

But there is more problem with `engine.c` cause we have no `fork, kill and pipe` functions.
Could it possiple to use similar concept like into `ddugovic's polyglot` for running engines?

https://github.com/ddugovic/polyglot

**Comment by lucasart** [comment]
not interested in windows compatibility at the moment. will be limited to POSIX envorinment like msys2 if using windows.
