### ISSUE TITLE
./c-chess-cli --version

### ISSUE THREAD

**Issue by vondele** [lucasart/c-chess-cli#43]
would be useful to have version output of the binary.

**Comment by lucasart** [comment]
Done: 32feb005d09454edc7db3436895fde0e629be052.

Version numbering is automated as YYYY-MM-DD, where the date is taken from git (as written in the repo, not the date when you compile, of course).

**Comment by lucasart** [comment]
looks like it broke MacOSX testing on github CI, due to python version...
https://github.com/lucasart/c-chess-cli/runs/2385747856

**Comment by lucasart** [comment]
done
