### ISSUE TITLE
Timeout during engine init.

### ISSUE THREAD

**Issue by Sopel97** [lucasart/c-chess-cli#44]
https://github.com/lucasart/c-chess-cli/blob/327b55e39530105a612af39ebd8e91583a68f1d9/src/engine.c#L152
https://github.com/lucasart/c-chess-cli/blob/327b55e39530105a612af39ebd8e91583a68f1d9/src/engine.c#L220

The timeout is hardcoded and I cannot test my largest nets for stockfish which take more time to load.

**Comment by vondele** [comment]
note that the issue is worse on networked file systems, where depending on the load the filesystem response can be really slow. I would increase the deadlines a little more. If an engine really hangs, getting the timeout after, say, 20s is no problem IMO.

**Comment by Sopel97** [comment]
The only fix I'll accept is to make it configurable through a CLI option

**Comment by lucasart** [comment]
done b29a2d394498cc358d525c0d8944ed0ea8d7d0bf. i haven't tested it, but i guess it should work.
