### ISSUE TITLE
Documentation: options.Hash=$X means what ? Megabytes or Gigabytes ?

### ISSUE THREAD

**Issue by Technologov** [lucasart/c-chess-cli#54]
Documentation: options.Hash=$X means what ? Megabytes or Gigabytes ?

Totally unclear to me.

**Comment by lucasart** [comment]
This has nothing to do with c-chess-cli, and should not be documented here. All c-chess-cli provides is the ability to communicate options to engines using the general syntax option.X=V. The fact that when X="Hash" and Y=16, engines interpret as meaning 16 MB for search Hash table is something that is merely recommended by the UCI protocol, and tends to be followed by UCI compliant engines.
