### ISSUE TITLE
CLI: lack of --help and --version command options

### ISSUE THREAD

**Issue by Technologov** [lucasart/c-chess-cli#55]
root@rampage-102:~/c-chess-cli# ./c-chess-cli --help
Unknown option '--help'
(Must show at least 3 example commands and most common options)

root@rampage-102:~/c-chess-cli# ./c-chess-cli --version
Unknown option '--version'

Those options are standard among Linux commands.

**Comment by lucasart** [comment]
`-version` is available. As for `-help`, please refer instead to the README file. Coding this means duplicating large parts of the read me file in the code, which is lame.

**Comment by Technologov** [comment]
is not lame; it needs to be done.
