### ISSUE TITLE
Timeout problems; SF14 crashes with c-chess-cli

### ISSUE THREAD

**Issue by Technologov** [lucasart/c-chess-cli#56]
root@rampage-102:/c-chess-cli# ./c-chess-cli -each tc=60+0.6  option.Threads=1     -engine cmd=./stockfish_14_x64_bmi2 option.Hash=16384     -engine cmd=./stockfish_8_x64_bmi2 option.Hash=1024     -games 10 -concurrency 2 -repeat     -draw number=40 count=8 score=10 -pgn out.pgn
[2] Started game 2 of 10 (Stockfish 8 64 BMI2 vs Stockfish 14)
[1] Started game 1 of 10 (Stockfish 14 vs Stockfish 8 64 BMI2)
[1] engine Stockfish 14 is unresponsive
root@rampage-102:~/c-chess-cli#

a test-run failed... looks like a Stockfish 14 crash.,
...
SF experts (Vondele & Aloril) say that SF14 didn't crash; just c-chess-cli is too impatient and expects immediate result. There must be some kind of timeout

**Comment by lucasart** [comment]
This was fixed already. See #46, and use timeout engine option if needed (4 seconds default is already enormous).

**Comment by vondele** [comment]
no, I think it happens still, but probably in a different way with master see last comment in #46.
