### ISSUE TITLE
Wrong "time forfeit" forced

### ISSUE THREAD

**Issue by francogrex** [lucasart/c-chess-cli#58]
What is this for (in game.c)
        
    if ((eo[ei]->time || eo[ei]->increment || eo[ei]->movetime) && timeLeft[ei] < 0) {
                g->state = STATE_TIME_LOSS;
                break;
            }
It is forcing an illegal time forfeit on some engines (e.g. berserk, xiphos). I suggest that it is not well implemented and should be revised/removed.

**Comment by lucasart** [comment]
Time is measured from the UI pov. The OS introduces unpredictable delays from task switching and I/O. The solution is that engines should have a time buffer (generally UCI option to control).
