### ISSUE TITLE
Error running on Windows

### ISSUE THREAD

**Issue by Dominiquini** [lucasart/c-chess-cli#62]
I'm getting this error when I try to run o Windows:

[2] error in src/engine.c: (94). No error

Command used:  
`c-chess-cli -each tc==4+0.04 option.Hash=8 option.Threads=1 -engine cmd='C:\ProgramData\Chess Engines\Stockfish\Stockfish_avx2.exe' -engine cmd='C:\ProgramData\Chess Engines\LCZero\lc0_GPU_CUDA.exe' -games 2 -concurrency 4 -log`

OS: Windows 10 x64
App: 2021-07-10

Thanks.

**Comment by lucasart** [comment]
Try removing those single quotes around paths. There is no logic in c-chess-cli to parse quotes, it's all delegated to the shell.
