### ISSUE TITLE
Readme.md suggestions

### ISSUE THREAD

**Issue by ppigazzini** [lucasart/c-chess-cli#7]
- there are both uppercase and lowercase after colon
- add a space after the first colon (more easy to read "`-<option> <value1>:` : gives `<value1>` to the first engine ...")
- perhaps this syntax could be more easy to read on the fly:
 
### Options
Syntax: `-<option> <value>`

List of `<option> <value>`:
* `concurrency c` : number of threads used to play games concurrently.
...

### Flags
Syntax: `-<flag>`

List of `<flag>`:

* `chess960` : use Chess960/FRC castling rules.
...

### Engine options
Syntax:

* `-<option> <value1>` : gives `<value1>` to both engines.
* `-<option> <value1>:<value2>` : gives `<value1>` to the first engine, and `<value2>` to the second engine.
* `-<option> <value1>:` : gives `<value1>` to the first engine, and nothing to the second.
* `-<option> :<value2>` : can you guess? good.

List of `<option> <value>`:
* `cmd <engine>` : command to run each engine.
* `name <new_name>` : name override for each engine. By default the name is read from id name following the UCI protocol.
* `movetime <float>` : time limit per move in seconds (default none).
* `nodes <int>` : node limit per move (default none).
* `options <comma_separated_UCI_options>` : list of UCI options per engine (default none).

**Comment by ppigazzini** [comment]
@lucasart I'm not able to follow the code :(, so please check if this PR https://github.com/cutechess/cutechess/pull/551 to generalize the book start option can be useful.

**Comment by lucasart** [comment]
Improved the readme. I also added some explicit examples on how to handle UCI options that contain spaces. That will easily trip many casual users, who don't understand much about the shell, and just want to know what to type for things to work.

**Comment by lucasart** [comment]
> @lucasart I'm not able to follow the code :(, so please check if this PR [cutechess/cutechess#551](https://github.com/cutechess/cutechess/pull/551) to generalize the book start option can be useful.

Not relevant in the context of c-chess-cli. There are only 2 possibilitied in c-chess-cli:
- default: start from the beginning, read sequentially.
- random: start from a random line, read sequentially.

I think cutechess is over-engineered, and I don't understand the value proposition here:
- random cutechess style: read every opening randomly. On average (in a distributed framework context), overlapping will be the same whether you do it cutechess style or c-chess style. The cutechess way just loses the performance from sequantial reading (buffering) for no reason.
- start from line N (modulo EOF after vondele's patch): sure, this is trvial to implement, but why? I don't like box-ticking for the sake of it. There has to be a valid reason for features to exist.

**Comment by ppigazzini** [comment]
In fishtest was measured that workers repeated the openings, due to several issues (worker seed, sequential read of book with ordered openings etc.). vondele's PR try to solve the problem, read here the analysis:
https://github.com/glinscott/fishtest/issues/478#issue-542154168

Another cutechess-cli limitation is that accept only integer for parameter used in tuning.

**Comment by lucasart** [comment]
I had a look, and couldn't find any convincing arguments, mostly hand waiving. 

the birthday paradox is inevitable. if you choose randomly from 2^16 openings, on average, you will have 1 collision every 2^8 = 256 games, which is negligible and completely fine in practice. Even with the same opening you get different games in real tc conditions on different machines with different background noise.

**Comment by lucasart** [comment]
of course I assume that you seed correctly the PRNG, where each worker uses different and unpredictable seed (which is what c-chess-cli does, by using the number of milliseconds since boot on the machine).

**Comment by ppigazzini** [comment]
> of course I assume that you seed correctly the PRNG, where each worker uses different and unpredictable seed (which is what c-chess-cli does, by using the number of milliseconds since boot on the machine).

So this could be a problem with big servers (170-250 threads) running fleets of 8-cores workers?

**Comment by lucasart** [comment]
Yes. You have a seeding problem. So there is no problem in cutechess, nor need to add any features to it. Every worker must have its own unpredictable and independant choice of seed.

Each machine must have its own seed, and using the number of clock ticks sinct boot time (clock_gettime) is the simplest way to to do this correctly. If for some reason, you have a logic where all workers in the same fleet start exactly at the same time (which I really doubt is possible, given sufficiently precise clock ticks), then you can always xor the machine id with the clock tick, for example (or better a hash of the machine id to spread the bits).

If there is a problem somewhere, it is a bug in cutechess, with the default seed initialization. The codebase is so enormous and scattered, I can't find my way around it. I see `Mersenne::random()`, but where is the call to `Mersenne::initialize(seed)` ? and what seed does it use ?

**Comment by ppigazzini** [comment]
Typos:
 - perform**s** a Sequ**a**ntial Probability Ratio Test 
 - perform a Sequential Probability Ratio Test
