### ISSUE TITLE
vector 

### ISSUE THREAD

**Issue by lucasart** [lucasart/c-chess-cli#8]
type generic vector in C (macros, header before pointer model).

use cases:
* move lists in gen
* pos list in game

**Comment by Chess13234** [comment]
There few of these on github:
https://github.com/eteran/c-vector (fairly small)
https://github.com/goldsborough/vector/blob/master/vector.h (C++ replica)
https://github.com/faragon/libsrt (contains fast vector in https://github.com/faragon/libsrt/blob/master/src/svector.c)

**Comment by lucasart** [comment]
I prefer to write my own code. If i just wanted to get thing working, I would use libsrt for everything (string, vector, hash map etc.). Or better yet, write c-chess-cli in Go instead of C. But this spoils the fun. The fun is in coding itself, not the result: reinventing the wheels is how you learn. Debugging, designing, having second thoughts about your design with hindsight, rewriting, etc. That's how you become a better programmer.

**Comment by lucasart** [comment]
I wrote a first patch, which shows you the design I'm going for. Doesn't implement anything yet, beyond new/del with RAII and len/alloc accessors.

**Comment by lucasart** [comment]
on second thoughts, this is not a goal in itself. program is feature complete, no need for bloat.
